name: Deploy Blazor WASM to GitHub Pages
on: 
    push:
        branches: [ master ]
permissions:
    contents: write
jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4.1.1
          
            - name: Setup .NET Core SDK 🔧
              uses: actions/setup-dotnet@v4.0.0
              with:
                  dotnet-version: 8.x

            - name: dotnet workload restore
              run: dotnet workload restore
            
            - name: Publish .NET Core Project
              run: dotnet publish Portfolio.csproj -c Release -o release --nologo

            - name: copy index.html to 404.html
              run: cp release/wwwroot/index.html release/wwwroot/404.html

            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll

            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4
              with:
                  BRANCH: gh-pages
                  FOLDER: release/wwwroot
